##
# Plugins
require:
  - standard
  - rubocop-rspec

##
# Defaults: standard-rb
inherit_gem:
  standard: config/base.yml

##
# Enabled
Style/FrozenStringLiteralComment:
  Enabled: true

##
# Disabled
Layout/MultilineMethodCallIndentation:
  Enabled: false
Style/TrivialAccessors:
  Enabled: false
Style/CommandLiteral:
  Enabled: false
